// A small fixture tree shared by `interpret.test.ts` and `complete.test.ts`: enough to
// exercise every command and completion rule without the real mount table or content.

import type { FsTree } from '~/fs/types';

export const tree: FsTree = {
  '/': {
    path: '/',
    name: '/',
    kind: 'dir',
    title: '/',
    children: ['/about.txt', '/resume.pdf', '/projects', '/drones', '/bin'],
  },
  '/about.txt': {
    path: '/about.txt',
    name: 'about.txt',
    kind: 'file',
    title: 'About',
    url: '/about/',
    srcUrl: '/fs/src/about.txt.txt',
  },
  '/resume.pdf': {
    path: '/resume.pdf',
    name: 'resume.pdf',
    kind: 'link',
    title: 'Resume PDF',
    href: '/resume.pdf',
    download: 'resume.pdf',
  },
  '/projects': {
    path: '/projects',
    name: 'projects',
    kind: 'dir',
    title: 'Projects',
    url: '/projects/',
    children: ['/projects/orbital-mesh'],
  },
  '/projects/orbital-mesh': {
    path: '/projects/orbital-mesh',
    name: 'orbital-mesh',
    kind: 'dir',
    title: 'Orbital Mesh',
    url: '/projects/orbital-mesh/',
    children: ['/projects/orbital-mesh/readme.md'],
  },
  '/projects/orbital-mesh/readme.md': {
    path: '/projects/orbital-mesh/readme.md',
    name: 'readme.md',
    kind: 'file',
    title: 'Orbital Mesh',
    url: '/projects/orbital-mesh/',
    srcUrl: '/fs/src/projects/orbital-mesh/readme.md.txt',
  },
  '/drones': {
    path: '/drones',
    name: 'drones',
    kind: 'dir',
    title: 'Drones',
    url: '/drones/',
    children: [],
  },
  '/bin': {
    path: '/bin',
    name: 'bin',
    kind: 'dir',
    title: 'bin',
    children: [
      '/bin/help',
      '/bin/ls',
      '/bin/cd',
      '/bin/pwd',
      '/bin/cat',
      '/bin/open',
      '/bin/whoami',
      '/bin/clear',
      '/bin/exit',
      '/bin/sudo',
      '/bin/rm',
      '/bin/arm',
      '/bin/disarm',
      '/bin/hack',
      '/bin/terminal.exe',
      '/bin/viewer.exe',
    ],
  },
  '/bin/help': { path: '/bin/help', name: 'help', kind: 'text', title: 'help', text: 'help' },
  '/bin/ls': { path: '/bin/ls', name: 'ls', kind: 'text', title: 'ls', text: 'ls' },
  '/bin/cd': { path: '/bin/cd', name: 'cd', kind: 'text', title: 'cd', text: 'cd' },
  '/bin/pwd': { path: '/bin/pwd', name: 'pwd', kind: 'text', title: 'pwd', text: 'pwd' },
  '/bin/cat': { path: '/bin/cat', name: 'cat', kind: 'text', title: 'cat', text: 'cat' },
  '/bin/open': { path: '/bin/open', name: 'open', kind: 'text', title: 'open', text: 'open' },
  '/bin/whoami': {
    path: '/bin/whoami',
    name: 'whoami',
    kind: 'text',
    title: 'whoami',
    text: 'whoami',
  },
  '/bin/clear': { path: '/bin/clear', name: 'clear', kind: 'text', title: 'clear', text: 'clear' },
  '/bin/exit': { path: '/bin/exit', name: 'exit', kind: 'text', title: 'exit', text: 'exit' },
  '/bin/sudo': { path: '/bin/sudo', name: 'sudo', kind: 'text', title: 'sudo', text: 'you first.' },
  '/bin/rm': { path: '/bin/rm', name: 'rm', kind: 'text', title: 'rm', text: "don't." },
  '/bin/arm': {
    path: '/bin/arm',
    name: 'arm',
    kind: 'text',
    title: 'arm',
    text: "you'll know when it's armed.",
  },
  '/bin/disarm': {
    path: '/bin/disarm',
    name: 'disarm',
    kind: 'text',
    title: 'disarm',
    text: "you'll know when it's not.",
  },
  '/bin/hack': { path: '/bin/hack', name: 'hack', kind: 'text', title: 'hack', text: 'do not.' },
  '/bin/terminal.exe': {
    path: '/bin/terminal.exe',
    name: 'terminal.exe',
    kind: 'app',
    title: 'terminal.exe',
    app: 'terminal',
  },
  '/bin/viewer.exe': {
    path: '/bin/viewer.exe',
    name: 'viewer.exe',
    kind: 'app',
    title: 'viewer.exe',
    app: 'viewer',
  },
};
